//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ProductId { get; set; }
        public System.Guid ProductUid { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
        public string Description { get; set; }
        public int CategoryId { get; set; }
        public int ManufacturerId { get; set; }
        public double Rating { get; set; }
        public decimal Price { get; set; }
        public int QuantityInStock { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public string DeliveryCountry { get; set; }
        public bool IsOnSale { get; set; }
        public decimal DiscountPercent { get; set; }
        public int PurchasedCount { get; set; }
        public byte[] ProductLogo { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
    }
}
