use UNIVER;

--1
select GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY,
ROUND(avg(cast(PROGRESS.NOTE as float)), 2) as [Средняя оценка]
from FACULTY
inner join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY like 'ТОВ'
group by rollup (GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY)

--2
select GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY,
ROUND(avg(cast(PROGRESS.NOTE as float)), 2) as [Средняя оценка]
from FACULTY
inner join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY like 'ТОВ'
group by cube (GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY)

--3
select GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY,
round(avg(cast(PROGRESS.NOTE as float)), 2) as [Средняя оценка]
from FACULTY
inner join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY like 'ТОВ'
group by GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY
union
--union all
select GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY,
round(avg(cast(PROGRESS.NOTE as float)), 2) as [Средняя оценка]
from FACULTY
inner join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY like 'ХТиТ'
group by GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY

--4
select GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY,
round(avg(cast(PROGRESS.NOTE as float)), 2) as [Средняя оценка]
from FACULTY
inner join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY like 'ТОВ'
group by GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY
intersect
select GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY,
round(avg(cast(PROGRESS.NOTE as float)), 2) as [Средняя оценка]
from FACULTY
inner join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY like 'ХТиТ'
group by GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY

--5
select GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY,
round(avg(cast(PROGRESS.NOTE as float)), 2) as [Средняя оценка]
from FACULTY
inner join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY like 'ТОВ'
group by GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY
except
select GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY,
round(avg(cast(PROGRESS.NOTE as float)), 2) as [Средняя оценка]
from FACULTY
inner join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY like 'ХТиТ'
group by GROUPS.PROFESSION, PROGRESS.SUBJECT, FACULTY.FACULTY