--1
SELECT AUDITORIUM.AUDITORIUM[Код аудитории], AUDITORIUM_TYPE.AUDITORIUM_TYPENAME[Тип аудитории]
FROM AUDITORIUM Inner Join AUDITORIUM_TYPE
On AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE

--2
SELECT AUDITORIUM.AUDITORIUM[Код аудитории], AUDITORIUM_TYPE.AUDITORIUM_TYPENAME[Наименование аудитории]
FROM AUDITORIUM Inner Join AUDITORIUM_TYPE
On AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE and AUDITORIUM_TYPE.AUDITORIUM_TYPENAME like '%компьютер%'

--3
SELECT DISTINCT FACULTY.FACULTY[Факультет], PULPIT.PULPIT[Кафедра], SUBJECT.SUBJECT[Дисциплина], STUDENT.NAME[Имя студента], PROGRESS.NOTE[Оценка], 
Case
when (PROGRESS.NOTE = 6) then 'шесть'
when (PROGRESS.NOTE = 7) then 'семь'
when (PROGRESS.NOTE = 8) then 'восемь'
else 'другая оценка'
end [Оценка]
FROM PROGRESS
inner join STUDENT on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
inner join SUBJECT on PROGRESS.SUBJECT = SUBJECT.SUBJECT
inner join PULPIT on SUBJECT.PULPIT = PULPIT.PULPIT
inner join FACULTY on FACULTY.FACULTY = PULPIT.FACULTY
inner join PROFESSION on PROFESSION.FACULTY = FACULTY.FACULTY
where PROGRESS.NOTE between 6 and 8
order by PROGRESS.NOTE desc

--4
select PULPIT.[PULPIT_NAME], isnull(TEACHER.TEACHER_NAME, '***')[Имя преподавателя]
FROM PULPIT left outer join TEACHER
On PULPIT.PULPIT = TEACHER.PULPIT

--5
SELECT*FROM AUDITORIUM_TYPE FULL OUTER JOIN AUDITORIUM
On AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
WHERE AUDITORIUM IS NULL

SELECT*FROM AUDITORIUM FULL OUTER JOIN AUDITORIUM_TYPE
On AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
WHERE AUDITORIUM IS NULL

SELECT*FROM AUDITORIUM FULL OUTER JOIN AUDITORIUM_TYPE
On AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
WHERE AUDITORIUM.AUDITORIUM_TYPE IS NOT NULL AND AUDITORIUM_TYPE.AUDITORIUM_TYPE IS NOT NULL

--6
SELECT AUDITORIUM_TYPE.AUDITORIUM_TYPE[Тип аудитории], AUDITORIUM.AUDITORIUM[Код аудитории]
FROM AUDITORIUM CROSS JOIN AUDITORIUM_TYPE
WHERE AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE

